services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork
  microservices1:
    image: openjdk:17
    container_name: microservices1
    build:
      context: ./microservices1
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/demo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpass
    depends_on:
      - mysql-db
    volumes:
      - ./microservice1/config:/config
      - logs-microservice-1:/logs
    networks:
      - mynetwork


# Explicitly define the volumes used in the services above
volumes:
  mysql-data:
    driver: local  # Ensures Docker uses local volumes for MySQL data
  logs-microservice-1:
    driver: local  # Volume for logs of microservice1


# Define custom network
networks:
  mynetwork:
    driver: bridge  # Use bridge network driver